document.writeln("");
document.writeln("	<!-- +++++ Footer Section +++++ -->");
document.writeln("<div id=\'footer\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("			<div class=\'row\'>");
document.writeln("				<div class=\'col-lg-4\'>");
document.writeln("					<h4>联系我</h4>");
document.writeln("					<p>");
document.writeln("						邮箱：zxwjob@qq.com<br/>");
document.writeln("						QQ：（即将上线）<br/>");
document.writeln("						Peing提问箱（即将上线）<br/>");
document.writeln("					</p>");
document.writeln("				</div><!-- /col-lg-4 -->");
document.writeln("				");
document.writeln("				<div class=\'col-lg-4\'>");
document.writeln("					<h4>社交平台</h4>");
document.writeln("					<p>");
document.writeln("						<a href=\'http://weibo.com/32113211\' target=\'_blank\'>微博</a><br/>");
document.writeln("						<a href=\'https://instagram.com/mrshallwe/\' target=\'_blank\'>Instagram</a><br/>");
document.writeln("						<a href=\'https://facebook.com/mrshallwe\' target=\'_blank\'>Facebook</a>");
document.writeln("					</p>");
document.writeln("				</div><!-- /col-lg-4 -->");
document.writeln("				");
document.writeln("				<div class=\'col-lg-4\'>");
document.writeln("					<h4>关于本网站</h4>");
document.writeln("					<h7>本站仅供交流学习使用，如有侵权，请立即联系删除。本网站为出于兴趣制作，如果您喜欢本网站，期待您的<a href=\'contribute.html\'>捐助</a>。</h7>");
document.writeln("					<!--<h7>感谢Freenom,GitHub,阿里云,问卷星提供技术支持。</h7><br/><br/>--></br/>");
document.writeln("				</div><!-- /col-lg-4 -->");
document.writeln("			");
document.writeln("			</div>");
document.writeln("		");
document.writeln("		</div>");
document.writeln("		<div class=\'container centered\'>");
document.writeln("			<h7>Copyright © 2019 SHALLWE.GA All rights reserved.</h7><br/>");
document.writeln("			</div>");
document.writeln("		");
document.writeln("		");
document.writeln("</div>");