document.writeln("");
document.writeln("");
document.writeln("    <link href=\'http://shallwe.ga/assets/css/bootstrap.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("");
document.writeln("    <link href=\'http://shallwe.ga/assets/css/main.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <script src=\'https://code.jquery.com/jquery-1.10.2.min.js\'></script>");
document.writeln("    ");
document.writeln("    ");
document.writeln("    <script type=\'application/x-javascript\'> addEventListener(\'load\', function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>");
document.writeln("");
document.writeln("");
document.writeln("  <link href=\'http://shallwe.ga/assets/vlog/css/style2.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\' />");
document.writeln("  ");
document.writeln("  ");
document.writeln("								<script type=\'text/javascript\' src=\'http://shallwe.ga/assets/vlog/js/modernizr.custom.min.js\'></script>    ");
document.writeln("								<link href=\'http://shallwe.ga/assets/vlog/css/popuo-box.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\'>");
document.writeln("								<script src=\'http://shallwe.ga/assets/vlog/js/jquery.magnific-popup.js\' type=\'text/javascript\'></script>");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("");
document.writeln("      <script src=\'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\'></script>");
document.writeln("      <script src=\'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("	  ");
document.writeln("   <style>");
document.writeln("		.divcss5{ text-indent:35px}");
document.writeln("		");
document.writeln("		#small-dialog1,#small-dialog2,#small-dialog3,#small-dialog4{");
document.writeln("			background: #EBEBEB;");
document.writeln("			padding: 0;");
document.writeln("			text-align: left;");
document.writeln("			max-width: 650px;");
document.writeln("			margin: 40px auto;");
document.writeln("			position: relative;");
document.writeln("			text-align:center;");
document.writeln("			");
document.writeln("			");
document.writeln("		.video-grids{");
document.writeln("			margin-bottom: 0px;");
document.writeln("						margin-top: 0px;");
document.writeln("			padding-bottom: 0px;");
document.writeln("			padding-top: 0px;");
document.writeln("			margin: 1em 0;");
document.writeln("");
document.writeln("		}");
document.writeln("}");
document.writeln("	</style>");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln("");
document.writeln("");
document.writeln("	<div id=\'grey\'>");
document.writeln("	    <div class=\'container\'>");
document.writeln("				<div class=\'col-lg-8 col-lg-offset-2 centered\'>");
document.writeln("					<img src=\'http://shallwe.ga/assets/img/user.png\' width=\'50px\' height=\'50px\'><h3>VLOG 视 频</h3>");
document.writeln("			</div>");
document.writeln("	    </div> ");
document.writeln("	</div>");
document.writeln("	");
document.writeln("	");
document.writeln("	<div class=\'breaking-news\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("		<div class=\'row centered\'>	");
document.writeln("			");
document.writeln("		<div class=\'col-lg-6\'>");
document.writeln("			<div class=\'video-grids\' style=\'margin:1em 0;\'>");
document.writeln("					<div class=\'col-md-12 video-grids-left\'>");
document.writeln("						<div class=\'video-grids-left1\'>");
document.writeln("							<img src=\'assets/vlog/images/v04.jpg\' align=\'center\' alt=\' \' class=\'img-responsive\'>");
document.writeln("							<a class=\'play-icon popup-with-zoom-anim\' href=\'#small-dialog4\'>");
document.writeln("									<span> </span>");
document.writeln("							</a>");
document.writeln("							<div class=\'video-grid-pos\'>");
document.writeln("								<ul>");
document.writeln("									<li>33:00 <label>|</label></li>");
document.writeln("									<li>2019-11-13 11:33:07</li>");
document.writeln("									");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("								");
document.writeln("								<div id=\'small-dialog4\' class=\'mfp-hide\'>");
document.writeln("																");
document.writeln("																");
document.writeln("								");
document.writeln("								<iframe src=\'//player.bilibili.com/player.html?aid=75517562&cid=129184116&page=1\' width=\'500\' height=\'281\' scrolling=\'no\' border=\'0\' frameborder=\'no\' framespacing=\'0\' allowfullscreen=\'true\'> </iframe>");
document.writeln("								");
document.writeln("								</div>");
document.writeln("");
document.writeln("								");
document.writeln("						</div>");
document.writeln("						<div>");
document.writeln("							<h4>ShallVLOG 04「林俊杰济南演唱会 And More」</h4>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<div class=\'clearfix\'> </div>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("");
document.writeln("			");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("	</div>");
document.writeln("	");
document.writeln("	</div>");
document.writeln("	");
document.writeln("		<div class=\'container centered\' style=\'padding-top:50px\'>");
document.writeln("	");
document.writeln("	</div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<script language=\'javascript\' type=\'text/javascript\' src=\'http://shallwe.ga/vlogmore.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	<script src=\'http://shallwe.ga/assets/vlog/js/bootstrap.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <script src=\'http://shallwe.ga/assets/js/bootstrap.min.js\'></script>");