document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\'zh-CN\'>");
document.writeln("  <head>");
document.writeln("    <meta charset=\'utf-8\'>");
document.writeln("    <meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge\'>");
document.writeln("    <meta name=\'viewport\' content=\'width=device-width, initial-scale=1.0\'>");
document.writeln("    <meta name=\'description\' content=\'\'>");
document.writeln("    <meta name=\'author\' content=\'\'>");
document.writeln("		<link rel=\'shortcut icon\' href=\'assets/img/user.png\'>");
document.writeln("");
document.writeln("    <title>VLOG - ShallWe官网</title>");
document.writeln("");
document.writeln("    <!-- Bootstrap core CSS -->");
document.writeln("    <link href=\'assets/css/bootstrap.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("");
document.writeln("    <!-- Custom styles for this template -->");
document.writeln("    <link href=\'assets/css/main.css\' rel=\'stylesheet\'>");
document.writeln("");
document.writeln("    <script src=\'https://code.jquery.com/jquery-1.10.2.min.js\'></script>");
document.writeln("    ");
document.writeln("    ");
document.writeln("    <script type=\'application/x-javascript\'> addEventListener(\'load\', function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>");
document.writeln("");
document.writeln("");
document.writeln("  <link href=\'assets/vlog/css/style2.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\' />");
document.writeln("  ");
document.writeln("<!-- pop-up-box -->");
document.writeln("								<script type=\'text/javascript\' src=\'assets/vlog/js/modernizr.custom.min.js\'></script>    ");
document.writeln("								<link href=\'assets/vlog/css/popuo-box.css\' rel=\'stylesheet\' type=\'text/css\' media=\'all\'>");
document.writeln("								<script src=\'assets/vlog/js/jquery.magnific-popup.js\' type=\'text/javascript\'></script>");
document.writeln("<!--//pop-up-box -->");
document.writeln("    ");
document.writeln("    ");
document.writeln("    ");
document.writeln("");
document.writeln("    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->");
document.writeln("    <!--[if lt IE 9]>");
document.writeln("      <script src=\'https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js\'></script>");
document.writeln("      <script src=\'https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js\'></script>");
document.writeln("    <![endif]-->");
document.writeln("   </head>");
document.writeln("");
document.writeln("  <body>");
document.writeln("   ");
document.writeln("   ");
document.writeln("   <style>");
document.writeln("		.divcss5{ text-indent:35px}");
document.writeln("		");
document.writeln("		#small-dialog1,#small-dialog2,#small-dialog3{");
document.writeln("			background: #EBEBEB;");
document.writeln("			padding: 0;");
document.writeln("			text-align: left;");
document.writeln("			max-width: 650px;");
document.writeln("			margin: 40px auto;");
document.writeln("			position: relative;");
document.writeln("			text-align:center;");
document.writeln("}");
document.writeln("	</style>");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln("   ");
document.writeln("     <!-- Static navbar -->");
document.writeln(" 	<script language=\'javascript\' type=\'text/javascript\' src=\'header.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	<!-- +++++ Welcome Section +++++ -->");
document.writeln("	<div id=\'grey\'>");
document.writeln("	    <div class=\'container\'>");
document.writeln("				<div class=\'col-lg-8 col-lg-offset-2 centered\'>");
document.writeln("					<img src=\'assets/img/user.png\' width=\'50px\' height=\'50px\'><h3>VLOG 视 频</h3>");
document.writeln("			</div><!-- /row -->");
document.writeln("	    </div> <!-- /container -->");
document.writeln("	</div><!-- /grey -->");
document.writeln("	");
document.writeln("	");
document.writeln("	<div class=\'breaking-news\'>");
document.writeln("		<div class=\'container\'>");
document.writeln("		<div class=\'row centered\'>	");
document.writeln("			");
document.writeln("			");
document.writeln("			");
document.writeln("			<!-- shallwe -->");
document.writeln("		<div class=\'col-lg-6\'>");
document.writeln("			<div class=\'video-grids\'>");
document.writeln("					<div class=\'col-md-12 video-grids-left\'>");
document.writeln("						<div class=\'video-grids-left1\'>");
document.writeln("							<img src=\'assets/vlog/images/v03.png\' align=\'center\' alt=\' \' class=\'img-responsive\'>");
document.writeln("							<a class=\'play-icon popup-with-zoom-anim\' href=\'#small-dialog3\'>");
document.writeln("									<span> </span>");
document.writeln("							</a>");
document.writeln("							<div class=\'video-grid-pos\'>");
document.writeln("								<ul>");
document.writeln("									<li>14:55 <label>|</label></li>");
document.writeln("									<li>2019-05-28 09:18:07</li>");
document.writeln("									");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("								");
document.writeln("								<div id=\'small-dialog3\' class=\'mfp-hide\'>");
document.writeln("																");
document.writeln("								<iframe src=\'//player.bilibili.com/player.html?aid=53833908&cid=94165776&page=1\' width=\'500\' height=\'281\' scrolling=\'no\' border=\'0\' frameborder=\'no\' framespacing=\'0\' allowfullscreen=\'true\'> </iframe>");
document.writeln("								");
document.writeln("								</div>");
document.writeln("");
document.writeln("								");
document.writeln("						</div>");
document.writeln("						<div>");
document.writeln("							<h4>ShallVLOG 03 「去青岛看林俊杰演唱会」</h4>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<div class=\'clearfix\'> </div>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		<div class=\'col-lg-6\'>");
document.writeln("			<div class=\'video-grids\'>");
document.writeln("					<div class=\'col-md-12 video-grids-left\'>");
document.writeln("						<div class=\'video-grids-left1\'>");
document.writeln("							<img src=\'assets/vlog/images/v02.JPG\' align=\'center\' alt=\' \' class=\'img-responsive\'>");
document.writeln("							<a class=\'play-icon popup-with-zoom-anim\' href=\'#small-dialog2\'>");
document.writeln("									<span> </span>");
document.writeln("							</a>");
document.writeln("							<div class=\'video-grid-pos\'>");
document.writeln("								<ul>");
document.writeln("									<li>03:53 <label>|</label></li>");
document.writeln("									<li>2019-05-27 15:51:42</li>");
document.writeln("									");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("								");
document.writeln("");
document.writeln("");
document.writeln("								<div id=\'small-dialog2\' class=\'mfp-hide\'>");
document.writeln("									");
document.writeln("									<iframe src=\'//player.bilibili.com/player.html?aid=53769636&cid=94056002&page=1\'  width=\'500\' height=\'281\' scrolling=\'no\' border=\'0\' frameborder=\'no\' framespacing=\'0\' allowfullscreen=\'true\'> </iframe>");
document.writeln("								");
document.writeln("								</div>");
document.writeln("");
document.writeln("								");
document.writeln("						</div>");
document.writeln("						<div>");
document.writeln("							<h4>ShallVLOG 02「五一假期在济南」</h4>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<div class=\'clearfix\'> </div>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("			");
document.writeln("		<div class=\'col-lg-6\'>");
document.writeln("			<div class=\'video-grids\'>");
document.writeln("					<div class=\'col-md-12 video-grids-left\'>");
document.writeln("						<div class=\'video-grids-left1\'>");
document.writeln("							<img src=\'assets/vlog/images/v01.JPG\' align=\'center\' alt=\' \' class=\'img-responsive\'>");
document.writeln("							<a class=\'play-icon popup-with-zoom-anim\' href=\'#small-dialog1\'>");
document.writeln("									<span> </span>");
document.writeln("							</a>");
document.writeln("							<div class=\'video-grid-pos\'>");
document.writeln("								<ul>");
document.writeln("									<li>01:51 <label>|</label></li>");
document.writeln("									<li>2019-04-22 08:50:17</li>");
document.writeln("									");
document.writeln("								</ul>");
document.writeln("							</div>");
document.writeln("								");
document.writeln("								<div id=\'small-dialog1\' class=\'mfp-hide\'>");
document.writeln("									<!--<iframe src=\'https://player.vimeo.com/video/145787219\' width=\'500\' height=\'281\' frameborder=\'0\' webkitallowfullscreen=\'\' mozallowfullscreen=\'\' allowfullscreen=\'\'></iframe> -->");
document.writeln("								<iframe src=\'//player.bilibili.com/player.html?aid=50114771&cid=87724861&page=1\' width=\'500\' height=\'281\' scrolling=\'no\' border=\'0\' frameborder=\'no\' framespacing=\'0\' allowfullscreen=\'true\'> </iframe>");
document.writeln("								</div>");
document.writeln("");
document.writeln("								");
document.writeln("						</div>");
document.writeln("						<div>");
document.writeln("							<h4>ShallVLOG 01「收到林俊杰演唱会门票的喜悦」</h4>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<div class=\'clearfix\'> </div>");
document.writeln("				</div>");
document.writeln("		</div>");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("		");
document.writeln("	</div>");
document.writeln("	");
document.writeln("	</div>");
document.writeln("	");
document.writeln("		<div class=\'container centered\' style=\'padding-top:50px\'>");
document.writeln("	");
document.writeln("	</div>");
document.writeln("<!-- //breaking-news -->");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("<script>");
document.writeln("	");
document.writeln("	");
document.writeln("									$(document).ready(function() {");
document.writeln("									$(\'.popup-with-zoom-anim\').magnificPopup({");
document.writeln("										type: \'inline\',");
document.writeln("										fixedContentPos: false,");
document.writeln("										fixedBgPos: true,");
document.writeln("										overflowY: \'auto\',");
document.writeln("										closeBtnInside: true,");
document.writeln("										preloader: false,");
document.writeln("										midClick: true,");
document.writeln("										removalDelay: 300,");
document.writeln("										mainClass: \'my-mfp-zoom-in\'");
document.writeln("									});");
document.writeln("																									");
document.writeln("									});");
document.writeln("</script>");
document.writeln("	");
document.writeln("	");
document.writeln("		");
document.writeln("");
document.writeln("	<script src=\'assets/vlog/js/bootstrap.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("	");
document.writeln("	");
document.writeln("	<!-- +++++ Footer Section +++++ -->");
document.writeln("	");
document.writeln("	<script language=\'javascript\' type=\'text/javascript\' src=\'footer.js\'></script>");
document.writeln("");
document.writeln("");
document.writeln("    <!-- Bootstrap core JavaScript");
document.writeln("    ================================================== -->");
document.writeln("    <!-- Placed at the end of the document so the pages load faster -->");
document.writeln("    <script src=\'assets/js/bootstrap.min.js\'></script>");
document.writeln("  </body>");
document.writeln("</html>");
document.writeln("");