document.writeln("<div class=\'navbar navbar-inverse navbar-static-top\'>");
document.writeln("      <div class=\'container\' style=\'padding-top:5px;padding-bottom:5px\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("          <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'.navbar-collapse\'>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("          </button>");
document.writeln("           <a class=\'navbar-brand\' href=\'../index.html\' style=\'padding-left:20px\'><img width=\'125px\' height=\'70px\' src=\'../assets/img/LOGOindex.png\'></a>");
document.writeln("         ");
document.writeln("          ");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <div class=\'navbar-collapse collapse\'>");
document.writeln("          <ul class=\'nav navbar-nav navbar-right\' style=\'padding-top:10px;padding-bottom:10px\'>");
document.writeln("          	<li><a href=\'../index.html\'>Home 主页</a></li>");
document.writeln("          	<li><a href=\'../recommend.html\'>Recommend 推荐</a></li>");
document.writeln("            <li><a href=\'../blog.html\'>Blog 博客</a></li>");
document.writeln("            <li><a href=\'../vlog.html\'>VLOG 视频</a></li>");
document.writeln("            <li><a href=\'../about.html\'>About 关于</a></li>");
document.writeln("            <li><a href=\'../contribute.html\'>Contribute 捐助</a></li>");
document.writeln("");
document.writeln("          </ul>");
document.writeln("        </div><!--/.nav-collapse -->");
document.writeln("      </div>");
document.writeln("   </div>");